### ISSUE TITLE
Don't block UI on font load

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaFrontend#1119]
## Overview
If analyzing the app loading (with "lighthouse" with instance), we can see that the display of the website is slowed down by the loading of some fonts which happens once the css has been loaded/parsed, which happens once the initial file has been loaded/parsed. The problem is quite common: https://web.dev/font-display/
![Screenshot 2022-08-01 at 17 05 03](https://user-images.githubusercontent.com/1053150/182180364-f5f597a7-f0f9-41be-9968-40d34ff94b14.png)

One way to solve that would be to [preload the blocking fonts](https://web.dev/font-display/#preload-web-fonts). That looks like the best solution to me. This requires to disable hashing for the fonts. 

Side question: why do we have so many fonts if only 3 are loaded at the end?

**Comment by Iloveall** [comment]
I've tried different way to make it work but it's quite difficult to implement it for Angular without postbuild tools/process.

Except hashed files there are also problem with duplicated requests and I assume this is because the paths in index.html and styles are different:

![Image](https://user-images.githubusercontent.com/7044736/204805090-81139028-dc65-4e90-a720-f70033e649f0.png)

All the problems described in this lib https://github.com/bfoese/ngx-preload-fonts#custom-base-href

So we can study their approach and use that way.

**Comment by smadbe** [comment]
Do you always have the duplicate in the current version of the app? I don't have, I don't have the first fetch (which would be the first thing fetch after the index.html while the index do not mention this font? I don't get it)

**Comment by smadbe** [comment]
Using a post-build is ok. `ngx-preload-fonts` can be used if you think it does the job.
