### ISSUE TITLE
Task link: open them in the same tab/window

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaFrontend#803]
**Describe the bug**
[This task](https://dev.algorea.org/en/#/activities/by-id/837046206729127555;path=4702,1352246428241737349,314613032161178344;attempId=0/details) contains links to other tasks (for instance, under 1)...: "activité en blockly") but when clicking on them, they open as new window on my browser (Firefox). (but the page is the right one!)

**Expected behavior**

The links should open these  tasks in the same window.

**Comment by ThomasJuster** [comment]
I think we already talked about this one :thinking: 
I understand the behavior is inappropriate considering the task, however the bug is not on AlgoreaFrontend side

From the task, we receive the parameters `{ "path": "…", "newTab": true }`. The spec says:
> newTab (boolean, optional) : open in a new tab/window

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/16257159/140910854-0d814b45-6d00-4eea-85a5-6a4a1c6253af.png)
</details>

**Comment by smadbe** [comment]
ok then 🤷‍♂️
